-- MySQL Script generated by MySQL Workbench
-- Tue Jan 21 16:21:41 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema logistica_almacenes
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema logistica_almacenes
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `logistica_almacenes` DEFAULT CHARACTER SET utf8 ;
USE `logistica_almacenes` ;

-- -----------------------------------------------------
-- Table `logistica_almacenes`.`almacenes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `logistica_almacenes`.`almacenes` ;

CREATE TABLE IF NOT EXISTS `logistica_almacenes`.`almacenes` (
  `localizacion` VARCHAR(250) NOT NULL,
  `nombre_nave` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`localizacion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `logistica_almacenes`.`camiones`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `logistica_almacenes`.`camiones` ;

CREATE TABLE IF NOT EXISTS `logistica_almacenes`.`camiones` (
  `matricula` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`matricula`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `logistica_almacenes`.`Trabajadores`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `logistica_almacenes`.`Trabajadores` ;

CREATE TABLE IF NOT EXISTS `logistica_almacenes`.`Trabajadores` (
  `idTrabajadores` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(250) NOT NULL,
  `apellidos` VARCHAR(250) NOT NULL,
  `direccion` VARCHAR(250) NOT NULL,
  `dni` VARCHAR(9) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `contraseña` VARCHAR(255) NOT NULL,
  `rol` VARCHAR(20) NOT NULL DEFAULT 'operario',
  `almacenes_localizacion` VARCHAR(250) NOT NULL,
  `camiones_matricula` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`idTrabajadores`),
  INDEX `fk_Trabajadores_almacenes1_idx` (`almacenes_localizacion` ASC) VISIBLE,
  INDEX `fk_Trabajadores_camiones1_idx` (`camiones_matricula` ASC) VISIBLE,
  CONSTRAINT `fk_Trabajadores_almacenes1`
    FOREIGN KEY (`almacenes_localizacion`)
    REFERENCES `logistica_almacenes`.`almacenes` (`localizacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Trabajadores_camiones1`
    FOREIGN KEY (`camiones_matricula`)
    REFERENCES `logistica_almacenes`.`camiones` (`matricula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `logistica_almacenes`.`pedidos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `logistica_almacenes`.`pedidos` ;

CREATE TABLE IF NOT EXISTS `logistica_almacenes`.`pedidos` (
  `idpedidos` INT NOT NULL AUTO_INCREMENT,
  `tipo_articulo` VARCHAR(250) NOT NULL,
  `status` VARCHAR(15) NOT NULL,
  `fecha_entrada` DATE NOT NULL,
  `fecha_salida` DATE NOT NULL,
  `origen` VARCHAR(100) NOT NULL,
  `destino` VARCHAR(100) NOT NULL,
  `almacenes_localizacion` VARCHAR(250) NOT NULL,
  `Trabajadores_almacenes_localizacion` VARCHAR(250) NOT NULL,
  `camiones_matricula` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`idpedidos`),
  INDEX `fk_pedidos_almacenes1_idx` (`almacenes_localizacion` ASC) VISIBLE,
  INDEX `fk_pedidos_Trabajadores1_idx` (`Trabajadores_almacenes_localizacion` ASC) VISIBLE,
  INDEX `fk_pedidos_camiones1_idx` (`camiones_matricula` ASC) VISIBLE,
  CONSTRAINT `fk_pedidos_almacenes1`
    FOREIGN KEY (`almacenes_localizacion`)
    REFERENCES `logistica_almacenes`.`almacenes` (`localizacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pedidos_Trabajadores1`
    FOREIGN KEY (`Trabajadores_almacenes_localizacion`)
    REFERENCES `logistica_almacenes`.`Trabajadores` (`almacenes_localizacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pedidos_camiones1`
    FOREIGN KEY (`camiones_matricula`)
    REFERENCES `logistica_almacenes`.`camiones` (`matricula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;