-- MySQL Script generated by MySQL Workbench
-- Thu Jan 23 18:57:53 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema logistica_almacen
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema logistica_almacen
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `logistica_almacen` DEFAULT CHARACTER SET utf8mb3 ;
USE `logistica_almacen` ;

-- -----------------------------------------------------
-- Table `logistica_almacen`.`warehouse`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `logistica_almacen`.`warehouse` ;

CREATE TABLE IF NOT EXISTS `logistica_almacen`.`warehouse` (
  `location` VARCHAR(250) NOT NULL,
  PRIMARY KEY (`location`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `logistica_almacen`.`truck`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `logistica_almacen`.`truck` ;

CREATE TABLE IF NOT EXISTS `logistica_almacen`.`truck` (
  `plate` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`plate`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `logistica_almacen`.`worker`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `logistica_almacen`.`worker` ;

CREATE TABLE IF NOT EXISTS `logistica_almacen`.`worker` (
  `id_worker` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(250) NOT NULL,
  `surname` VARCHAR(250) NOT NULL,
  `address` VARCHAR(250) NOT NULL,
  `dni` VARCHAR(9) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `role` VARCHAR(20) NOT NULL DEFAULT 'operario',
  `warehouse_location` VARCHAR(250) NOT NULL,
  `truck_plate` VARCHAR(10) NULL DEFAULT NULL,
  PRIMARY KEY (`id_worker`),
  INDEX `fk_Trabajadores_almacenes1_idx` (`warehouse_location` ASC) VISIBLE,
  INDEX `fk_Trabajadores_camiones1_idx` (`truck_plate` ASC) VISIBLE,
  CONSTRAINT `fk_Trabajadores_almacenes1`
    FOREIGN KEY (`warehouse_location`)
    REFERENCES `logistica_almacen`.`warehouse` (`location`),
  CONSTRAINT `fk_Trabajadores_camiones1`
    FOREIGN KEY (`truck_plate`)
    REFERENCES `logistica_almacen`.`truck` (`plate`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `logistica_almacen`.`order`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `logistica_almacen`.`order` ;

CREATE TABLE IF NOT EXISTS `logistica_almacen`.`order` (
  `id_order` INT NOT NULL AUTO_INCREMENT,
  `item_type` VARCHAR(250) NOT NULL,
  `status` VARCHAR(15) NOT NULL,
  `date_of_entry` DATE NOT NULL,
  `date_of_departure` DATE NOT NULL,
  `origin` VARCHAR(100) NOT NULL,
  `destination` VARCHAR(100) NOT NULL,
  `worker_id_worker` INT NOT NULL,
  `warehouse_location` VARCHAR(250) NOT NULL,
  `truck_plate` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`id_order`),
  INDEX `fk_order_worker1_idx` (`worker_id_worker` ASC) VISIBLE,
  INDEX `fk_order_warehouse1_idx` (`warehouse_location` ASC) VISIBLE,
  INDEX `fk_order_truck1_idx` (`truck_plate` ASC) VISIBLE,
  CONSTRAINT `fk_order_worker1`
    FOREIGN KEY (`worker_id_worker`)
    REFERENCES `logistica_almacen`.`worker` (`id_worker`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_order_warehouse1`
    FOREIGN KEY (`warehouse_location`)
    REFERENCES `logistica_almacen`.`warehouse` (`location`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_order_truck1`
    FOREIGN KEY (`truck_plate`)
    REFERENCES `logistica_almacen`.`truck` (`plate`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb3;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
